[theme]
# Primary accent color for interactive elements - Code8 brand orange/red
primaryColor = "#FF6B35"

# Background color for the main content area - Dark professional
backgroundColor = "#0E1117"

# Background color used for the sidebar and most interactive widgets - Darker gray
secondaryBackgroundColor = "#1E2124"

# Color used for almost all text - Clean white
textColor = "#FFFFFF"

[client]
toolbarMode = "minimal"