# SUPABASE
SUPABASE_URL = "https://xvybpsrxzrzosztqzclq.supabase.co",
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2eWJwc3J4enJ6b3N6dHF6Y2xxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNjA5NDMsImV4cCI6MjA2ODkzNjk0M30.fXiBfbhwfaaUjkVE5TpHNLoJBdEWIacn27MLKDeIUVs"

# SWIFT
SWIFT_KEY = "59CgKNgyylIwPRAFpcR9vdQdE+7aX6RuBUCul1u9fgAZCdS0E29+wE3fGTj4gU1oOY9W1Nl6dLAOZ6MB0354dg=="

# VALOR
VALOR_USER = "codeEight"
VALOR_PASSWORD = "valorCode25!"
valor_CLIENT_ID = "7k1tbckplqbgrjmk2agn7bqgsl"
VALOR_USER_POOL_ID = "us-east-1_XpppQGHdg"

# HAWKIN DYNAMICS
HD_REGION = "Americas"
HD_TOKEN = "ykPuH3.I7LYALG4Gs4yAamPHnz5O27nTjvoR"
HD_ORG_NAME = "dev"